# Generated by Django 4.1.2 on 2022-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250, null=True)),
                ('work', models.CharField(max_length=250, null=True)),
                ('experience', models.CharField(max_length=250, null=True)),
                ('rememberMe', models.BooleanField(default=False)),
                ('education', models.CharField(max_length=200, null=True)),
                ('about', models.CharField(max_length=500, null=True)),
                ('bio', models.CharField(max_length=1000, null=True)),
                ('linkedIn', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200, null=True)),
                ('twitter', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('profilePic', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
