# Generated by Django 4.1.2 on 2022-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_comment_p_id'),
        ('account', '0003_alter_userfollowing_following_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedPosts',
            field=models.ManyToManyField(blank=True, related_name='liked', to='products.product'),
        ),
    ]
