# Generated by Django 4.1.2 on 2022-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_comment_p_id'),
        ('account', '0004_user_likedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedPosts',
            field=models.ManyToManyField(blank=True, related_name='saved', to='products.product'),
        ),
    ]
