# Generated by Django 4.1.2 on 2022-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comment_dislikescount_comment_likescount'),
        ('account', '0005_user_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislikedComments',
            field=models.ManyToManyField(blank=True, related_name='dislikedComment', to='products.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='likedComments',
            field=models.ManyToManyField(blank=True, related_name='likedComment', to='products.comment'),
        ),
    ]
