# Generated by Django 4.1.2 on 2022-10-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_following_user_id_userfollowing_following_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='user_id',
        ),
    ]
