# Generated by Django 4.1.2 on 2022-10-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='p_id',
        ),
    ]
