# Generated by Django 4.1.2 on 2022-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_comment_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
